- name: create ec2 and r53
  hosts: local
  connections: local 
  vars:
   ami_id: ami-09c813fb71547fc4f
   sg_id: sg-0a6fb7b3161cf099d
   zone_id: "Z0048064LID2MWLWZVV8"
   domain_name: "daws86pavan.cyou"
   instancees:
   - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output
  
  - name: print the ec2_output
    ansible.builtin.debug:
     msg: "{{ ec2_output }}"