- name: setup mysql server
  hosts: mysql
  become: yes
  tasks:
- names: install mysql server
  ansible.builtin.package:
    name: mysql-server
    state: present 

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  ansiible.buitlin.coomand: mysql_secure_installation --set-root-pass Roboshop@1